// ui/src/pages/search/SearchResult.tsx
import { Container } from "@material-ui/core";
import VisibilitySensor from "react-visibility-sensor";
import { WordCard } from "../../components/search/WordCardComponent";
import { TemplateCard } from "../../components/search/TemplateCardComponent";
import { DataCard } from "../../components/search/DataCardComponent";
import { MGIDCard } from "../../components/search/MGIDCardComponent";
import { sortListElem } from "../../common/Utils";

type SearchResultProps = {
  resultMergedList: sortListElem[];
  query: string;
  isLoaded: boolean;
  isClicked: boolean;
  isAuthed: boolean;
  setLastCardVisible: React.Dispatch<React.SetStateAction<boolean>>;
};

const SearchResult: React.FC<SearchResultProps> = ({
  resultMergedList,
  query,
  isLoaded,
  isClicked,
  isAuthed,
  setLastCardVisible,
}) => {
  function onSensorChange(isVisible: boolean) {
    setLastCardVisible(isVisible);
  }
  if (!isClicked) {
    return null;
  }

  if (!isLoaded) {
    return <div>未搜索到相关结果...</div>;
  } else {
    return (
      <Container>
        {resultMergedList.map((item, index) => {
          const currentCard =
            item.type === "word" ? (
              <WordCard
                key={"word" + index}
                item={item.wordValue!}
                query={query}
                loggedIn={isAuthed}
              />
            ) : item.type === "template" ? (
              <TemplateCard
                key={"template" + index}
                item={item.templateValue!}
                query={query}
                loggedIn={isAuthed}
              />
            ) : item.type === "data" ? (
              <DataCard
                key={"data" + index}
                item={item.dataValue!}
                query={query}
                loggedIn={isAuthed}
              />
            ) : (
              <MGIDCard
                key={"MGID" + index}
                item={item.MGIDValue!}
                query={query}
                loggedIn={isAuthed}
              />
            );
          return index === resultMergedList.length - 1 ? (
            <VisibilitySensor key={index} onChange={onSensorChange}>
              {currentCard}
            </VisibilitySensor>
          ) : (
            currentCard
          );
        })}
      </Container>
    );
  }
};

const resultComponent = {
  SearchResult,
};

export default resultComponent;

// ui-vue/src/components/search/SearchResult.vue
<template>
  <div class="search-results">
    <div v-if="!isLoaded && isClicked" class="no-results">
      未搜索到相关结果...
    </div>
    <div v-else-if="isLoaded" class="results-list">
      <template v-for="(item, index) in resultMergedList" :key="index">
        <WordCard
          v-if="item.type === 'word'"
          :item="item.wordValue"
          :query="query"
          :loggedIn="isAuthed"
        />
        <TemplateCard
          v-else-if="item.type === 'template'"
          :item="item.templateValue"
          :query="query"
          :loggedIn="isAuthed"
        />
        <DataCard
          v-else-if="item.type === 'data'"
          :item="item.dataValue"
          :query="query"
          :loggedIn="isAuthed"
        />
        <MGIDCard
          v-else-if="item.type === 'MGID'"
          :item="item.MGIDValue"
          :query="query"
          :loggedIn="isAuthed"
        />
      </template>
    </div>
  </div>
</template>

<script setup lang="ts">
import { defineProps } from 'vue';
import WordCard from './WordCard.vue';
import TemplateCard from './TemplateCard.vue';
import DataCard from './DataCard.vue';
import MGIDCard from './MGIDCard.vue';
import { Word } from '../../api/WordService';
import { Template } from '../../api/TemplateService';
import { DevelopmentData } from '../../api/DevelopmentDataService';
import { MGIDApply } from '../../api/MGIDApplyService';

// Define a union type for the merged list items
export type SortListElem = 
  | { type: 'word'; wordValue: Word }
  | { type: 'template'; templateValue: Template }
  | { type: 'data'; dataValue: DevelopmentData }
  | { type: 'MGID'; MGIDValue: MGIDApply };

const props = defineProps<{
  resultMergedList: SortListElem[];
  query: string;
  isLoaded: boolean;
  isClicked: boolean;
  isAuthed: boolean;
}>();
</script>

<style scoped>
.search-results {
  max-width: 800px;
  margin: 0 auto;
  padding: 0 20px;
}

.no-results {
  text-align: center;
  color: #6b7280;
  margin-top: 40px;
}

.results-list {
  display: flex;
  flex-direction: column;
  gap: 16px;
}
</style>
